<?php

/**
 * BasePerfil
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property date $fecha_nacimiento
 * @property integer $sf_guard_user_id
 * @property sfGuardUser $User
 * @property Agenda $Agenda
 * 
 * @method integer     getId()               Returns the current record's "id" value
 * @method date        getFechaNacimiento()  Returns the current record's "fecha_nacimiento" value
 * @method integer     getSfGuardUserId()    Returns the current record's "sf_guard_user_id" value
 * @method sfGuardUser getUser()             Returns the current record's "User" value
 * @method Agenda      getAgenda()           Returns the current record's "Agenda" value
 * @method Perfil      setId()               Sets the current record's "id" value
 * @method Perfil      setFechaNacimiento()  Sets the current record's "fecha_nacimiento" value
 * @method Perfil      setSfGuardUserId()    Sets the current record's "sf_guard_user_id" value
 * @method Perfil      setUser()             Sets the current record's "User" value
 * @method Perfil      setAgenda()           Sets the current record's "Agenda" value
 * 
 * @package    theeventmachine
 * @subpackage model
 * @author     grode
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePerfil extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('perfil');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('fecha_nacimiento', 'date', null, array(
             'type' => 'date',
             'notnull' => false,
             ));
        $this->hasColumn('sf_guard_user_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'sf_guard_user_id',
             'foreign' => 'id'));

        $this->hasOne('Agenda', array(
             'local' => 'id',
             'foreign' => 'perfil_id'));
    }
}