<?php

/**
 * BaseAgendaEvento
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $agenda_id
 * @property integer $evento_id
 * @property Agenda $Agenda
 * @property Evento $Evento
 * 
 * @method integer      getAgendaId()  Returns the current record's "agenda_id" value
 * @method integer      getEventoId()  Returns the current record's "evento_id" value
 * @method Agenda       getAgenda()    Returns the current record's "Agenda" value
 * @method Evento       getEvento()    Returns the current record's "Evento" value
 * @method AgendaEvento setAgendaId()  Sets the current record's "agenda_id" value
 * @method AgendaEvento setEventoId()  Sets the current record's "evento_id" value
 * @method AgendaEvento setAgenda()    Sets the current record's "Agenda" value
 * @method AgendaEvento setEvento()    Sets the current record's "Evento" value
 * 
 * @package    theeventmachine
 * @subpackage model
 * @author     grode
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAgendaEvento extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('agenda_evento');
        $this->hasColumn('agenda_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('evento_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Agenda', array(
             'local' => 'agenda_id',
             'foreign' => 'id'));

        $this->hasOne('Evento', array(
             'local' => 'evento_id',
             'foreign' => 'id'));
    }
}