<?php

/**
 * BaseAgenda
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nombre
 * @property integer $perfil_id
 * @property Doctrine_Collection $Eventos
 * @property Perfil $Perfil
 * @property Doctrine_Collection $AgendaEvento
 * 
 * @method integer             getId()           Returns the current record's "id" value
 * @method string              getNombre()       Returns the current record's "nombre" value
 * @method integer             getPerfilId()     Returns the current record's "perfil_id" value
 * @method Doctrine_Collection getEventos()      Returns the current record's "Eventos" collection
 * @method Perfil              getPerfil()       Returns the current record's "Perfil" value
 * @method Doctrine_Collection getAgendaEvento() Returns the current record's "AgendaEvento" collection
 * @method Agenda              setId()           Sets the current record's "id" value
 * @method Agenda              setNombre()       Sets the current record's "nombre" value
 * @method Agenda              setPerfilId()     Sets the current record's "perfil_id" value
 * @method Agenda              setEventos()      Sets the current record's "Eventos" collection
 * @method Agenda              setPerfil()       Sets the current record's "Perfil" value
 * @method Agenda              setAgendaEvento() Sets the current record's "AgendaEvento" collection
 * 
 * @package    theeventmachine
 * @subpackage model
 * @author     grode
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAgenda extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('agenda');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('perfil_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Evento as Eventos', array(
             'refClass' => 'AgendaEvento',
             'local' => 'agenda_id',
             'foreign' => 'evento_id'));

        $this->hasOne('Perfil', array(
             'local' => 'perfil_id',
             'foreign' => 'id'));

        $this->hasMany('AgendaEvento', array(
             'local' => 'id',
             'foreign' => 'agenda_id'));
    }
}