<?php

/**
 * BaseEvento
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $descripcion
 * @property date $fecha_inicio
 * @property date $fecha_fin
 * @property boolean $repetir
 * @property Doctrine_Collection $Agendas
 * @property Doctrine_Collection $AgendaEvento
 * 
 * @method integer             getId()           Returns the current record's "id" value
 * @method string              getDescripcion()  Returns the current record's "descripcion" value
 * @method date                getFechaInicio()  Returns the current record's "fecha_inicio" value
 * @method date                getFechaFin()     Returns the current record's "fecha_fin" value
 * @method boolean             getRepetir()      Returns the current record's "repetir" value
 * @method Doctrine_Collection getAgendas()      Returns the current record's "Agendas" collection
 * @method Doctrine_Collection getAgendaEvento() Returns the current record's "AgendaEvento" collection
 * @method Evento              setId()           Sets the current record's "id" value
 * @method Evento              setDescripcion()  Sets the current record's "descripcion" value
 * @method Evento              setFechaInicio()  Sets the current record's "fecha_inicio" value
 * @method Evento              setFechaFin()     Sets the current record's "fecha_fin" value
 * @method Evento              setRepetir()      Sets the current record's "repetir" value
 * @method Evento              setAgendas()      Sets the current record's "Agendas" collection
 * @method Evento              setAgendaEvento() Sets the current record's "AgendaEvento" collection
 * 
 * @package    theeventmachine
 * @subpackage model
 * @author     grode
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEvento extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('evento');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('descripcion', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('fecha_inicio', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('fecha_fin', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('repetir', 'boolean', null, array(
             'type' => 'boolean',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Agenda as Agendas', array(
             'refClass' => 'AgendaEvento',
             'local' => 'evento_id',
             'foreign' => 'agenda_id'));

        $this->hasMany('AgendaEvento', array(
             'local' => 'id',
             'foreign' => 'evento_id'));
    }
}