<?php

/**
 * AgendaEventoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AgendaEventoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AgendaEventoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AgendaEvento');
    }
}