<?php

/**
 * EventoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EventoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EventoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Evento');
    }
    
       
    public function findByAgendaIdQuery($agenda_id)
    {
        return $this->createQuery('e')
                    ->innerJoin('e.Agendas a')
                    ->where('a.id = ?', $agenda_id)
                    ->orderBy("e.inicio DESC");   
    }
    
    public function findByAgendaId($agenda_id, $hydrationMode = DOCTRINE::HYDRATE_RECORD)
    { 
        return $this->findByAgendaIdQuery($agenda_id)
                    ->execute(array(), $hydrationMode);
        
    }
    
    
    
    
}