<?php

/**
 * Evento
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    theeventmachine
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Evento extends BaseEvento
{
    public function __toString() {
        return $this->getTitulo();
    }
    
    public function getInicioFormateado() {
        return date('d/m/Y', strtotime($this->getInicio()));
    }
    
    // Agrega a la representacion de array, nuevos campos cuyos 
    // nombres estan en ingles (los usa fullCalendar)
    public function toFullCalendarArray() {
        $arr = $this->toArray();
        
        $arr['title']  = $arr['titulo'];
        $arr['allDay'] = $arr['diario'];
        $arr['start']  = date('Y-m-d\TH:i:s', strtotime($arr['inicio'])); 
        $arr['end']    = date('Y-m-d\TH:i:s', strtotime($arr['fin'])); 
        
        return $arr;
    }
    
    
    
    
}