# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html
    
  metas:
    title:        The Event Machine
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [bootstrap.min.css, sticky-footer-navbar.css, columnas-aplicacion-principal.css]

  javascripts:    [jquery-1.11.2.min.js, bootstrap.min.js, moment.min.js, fullcalendar.min.js, es.js, menu.js, jquery.validation_status_tracker.js, jquery.exsieve.js, event-list.js]

  has_layout:     true
  layout:         layout
