Evento:
  tableName: evento
  columns:
    id: 
      type: integer(4)
      autoincrement: true
      primary: true
      notnull: true
    descripcion:
      type: string(255)
    fecha_inicio:
      type: date
    fecha_fin:
      type: date
    repetir:
      type: boolean
  relations:
    Agendas:
      class: Agenda
      refClass: AgendaEvento
      local: evento_id
      foreign: agenda_id 
      foreignAlias: Agendas

Agenda:
  tableName: agenda
  columns:
    id: 
      type: integer(4)
      autoincrement: true
      primary: true
      notnull: true  
    nombre:
      type: string(255)
  relations:
    Eventos:
      class: Evento
      refClass: AgendaEvento
      local: agenda_id
      foreign: evento_id
      foreignAlias: Eventos
      
AgendaEvento:
  columns:
    agenda_id:
      type: integer(4)
      primary: true
    evento_id:
      type: integer(4)
      primary: true
  relations:
    Agenda:
      local: agenda_id
      foreign: id  
    Evento:
      local: evento_id
      foreign: id