Evento:
  tableName: evento
  columns:
    id: 
      type: integer(4)
      autoincrement: true
      primary: true
      notnull: true
    identificador: 
      type: integer
      notnull: false
      comment: "Uniquely identifies the given event. Different instances of repeating events should all have the same id."      
    titulo:  
      type: string(255)
      notnull: true
      comment: "The text on an event's element"
    diario:  
      type: boolean
      notnull: false
      comment: "Whether an event occurs at a specific time-of-day. This property affects whether an event's time is shown"
    descripcion:  
      type: string(255)
      notnull: true
    inicio:  
      type: timestamp
      notnull: true
      comment: "The date/time an event begins"
    fin:  
      type: timestamp
      notnull: false
      comment: "The exclusive date/time an event ends. It is the moment immediately after the event has ended. For example, if the last full day of an event is Thursday, the exclusive end of the event will be 00:00:00 on Friday!"
    repetir:
      type: boolean
      notnull: false
    url:
      type: string(2000)
      notnull: false
      comment: "A URL that will be visited when this event is clicked by the user. For more information on controlling this behavior, see the eventClick callback."
    editable:
      type: boolean
      notnull: false
      comment: "Overrides the master editable option for this single event."
  relations:
    Agendas:
      class: Agenda
      refClass: AgendaEvento
      local: evento_id
      foreign: agenda_id 
      foreignAlias: Agendas

Perfil:
  columns:
    id: 
      type: integer(4)
      autoincrement: true
      primary: true
      notnull: true  
    fecha_nacimiento:
      type: date
      notnull: false    
    sf_guard_user_id: integer
  relations:
    User:
      class: sfGuardUser
      foreignType: one
      local: sf_guard_user_id
      foreign: id
      

Agenda:
  tableName: agenda
  columns:
    id: 
      type: integer(4)
      autoincrement: true
      primary: true
      notnull: true  
    nombre:
      type: string(255)
    perfil_id:
      type: integer(4)
      notnull: true
  relations:
    Eventos:
      class: Evento
      refClass: AgendaEvento
      local: agenda_id
      foreign: evento_id
      foreignAlias: Eventos
    Perfil:
      class: Perfil
      foreignType: one
      local: perfil_id
      foreign: id
      
      
      
AgendaEvento:
  columns:
    agenda_id:
      type: integer(4)
      primary: true
    evento_id:
      type: integer(4)
      primary: true
  relations:
    Agenda:
      local: agenda_id
      foreign: id  
    Evento:
      local: evento_id
      foreign: id