generator:
  class: sfDoctrineGenerator
  param:
    config:
      form:
        class: sfGuardUserAdminForm
        display:
          "User":                   [first_name, last_name, email_address, username, password, password_again, Perfil]
          "Permissions and groups": [is_active, is_super_admin, groups_list, permissions_list]